### ISSUE TITLE
Doesn't bypass void obf

### ISSUE THREAD

**Issue by ghost** [dekrypted/KryptDis#2]

**Comment by vjnu** [comment]
Because void obfuscation is the best and that's a fact.

**Comment by dekrypted** [comment]
shut the fuck up 😄

**Comment by ghost** [comment]
> Because void obfuscation is the best and that's a fact.

True and I agree

**Comment by dekrypted** [comment]
> Because void obfuscation is the best and that's a fact.

what even is void obfuscation 💀

**Comment by ghost** [comment]
The best Python™️ obfuscator on the market.

**Comment by 0verp0wer** [comment]
> The best Python™️ obfuscator on the market.

send llink

**Comment by dekrypted** [comment]
> > The best Python™️ obfuscator on the market.
> 
> send llink

💀

**Comment by 0verp0wer** [comment]
> > > The best Python™️ obfuscator on the market.
> > 
> > 
> > send llink
> 
> 💀

I Just want to see if It is really "the best obfuscator on the market"

**Comment by gumbobr0t** [comment]
just wanted to remind y'all that there is no good python obfuscation at all

**Comment by dekrypted** [comment]
> just wanted to remind y'all that there is no good python obfuscation at all

straight FACTS
